name: flutter_bloc_side_effect
description: Extended BLoC with second stream of Side Effects and widgets.
version: 1.0.0
homepage: https://github.com/AndreySosnovyy/bloc_side_effect
repository: https://github.com/AndreySosnovyy/bloc_side_effect
issue_tracker: https://github.com/AndreySosnovyy/bloc_side_effect/issues
topics:
  - bloc
  - state-management
  - side-effect

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
